# Generated by Django 3.1.5 on 2021-04-11 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20210409_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.CharField(default='0.00', max_length=255, verbose_name='amounts'),
        ),
    ]
