# Generated by Django 3.1.5 on 2021-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20210411_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='earned_profits',
            field=models.CharField(default='0.00', max_length=150),
        ),
    ]
