# Generated by Django 3.1.5 on 2021-04-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_accounts_earned_profits'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
