# Generated by Django 3.1.5 on 2021-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20210415_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='chain_id',
            field=models.CharField(default='new', max_length=150, verbose_name='chain_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(default='new', max_length=150, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='chain_id',
            field=models.CharField(default=0, max_length=150, verbose_name='chain_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default=0, max_length=150, verbose_name='status'),
            preserve_default=False,
        ),
    ]
