# Generated by Django 3.1.5 on 2021-04-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20210415_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='url',
            field=models.CharField(default='https://www.coinbase.com', max_length=200, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='url',
            field=models.CharField(default='https://www.coinbase.com', max_length=200, verbose_name='url'),
            preserve_default=False,
        ),
    ]
