# Generated by Django 3.1.5 on 2021-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20210416_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='packages',
            field=models.CharField(default='BASIC', max_length=150, verbose_name='packages'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='packages',
            field=models.CharField(default='BASIC', max_length=150, verbose_name='packages'),
        ),
    ]
